[project]
name = "trade-view"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Travis Cammack", email = "traviscammack@protonmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.141.1",
    "httpx>=0.28.1",
    "jinja2>=3.1.6",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "pyjwt>=2.14.0",
]

[project.scripts]
trade-view = "trade_view:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
